name = "my-toilet-blog"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "my-toilet-blogs"
database_id = "ac14b100-c26a-4a60-8407-68bcad02299a"